### ISSUE TITLE
github actions没有读写权限

### ISSUE THREAD

**Issue by lovelyCARDINAL** [moepad/zh-mainpage#1]
@dragon-fish https://github.com/moepad/zh-mainpage/settings/actions

**Comment by dragon-fish** [comment]
https://github.com/moepad/zh-mainpage/blob/7241145eaa5a1cbc912223b2cabc35234a27570e/src/index.ts#L1C25-L1C25 这个

**Comment by dragon-fish** [comment]
You can specify more granular permissions in the workflow using YAML. [Learn more about managing permissions.](https://docs.github.com/actions/reference/authentication-in-a-workflow#modifying-the-permissions-for-the-github_token)
